# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mllpong < Formula
  desc "A lightweight mock server for HL7 v2 messages over MLLP — always-ACK, always-NACK, and rule-based smart handler"
  homepage "https://mllpong.novalagung.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_darwin_amd64.tar.gz"
      sha256 "ef9f212b72eeba1bb63e7e856a051c97ae1c1ac05f41173445b72730ce2473df"

      define_method(:install) do
        bin.install "mllpong"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_darwin_arm64.tar.gz"
      sha256 "779ef2c1630fd8655af38d1c597cd9e265b478b497b44a3c8cb82320fc994918"

      define_method(:install) do
        bin.install "mllpong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_linux_amd64.tar.gz"
      sha256 "9ddabb1ed0970b3b2e11a4749739f481d14ad6e962808c491383d7bf6616603c"
      define_method(:install) do
        bin.install "mllpong"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_linux_arm64.tar.gz"
      sha256 "a3c40ac297747b55386c2ba30c55826df85142cee668186ec7acaa97d6ae5825"
      define_method(:install) do
        bin.install "mllpong"
      end
    end
  end
end
