# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mllpong < Formula
  desc "A lightweight mock server for HL7 v2 messages over MLLP — always-ACK, always-NACK, and rule-based smart handler"
  homepage "https://mllpong.novalagung.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_darwin_amd64.tar.gz"
      sha256 "ee8007247e7aa15f1e6a029c2830e620184a0375f5c62cb869bb6d4409dfedc4"

      define_method(:install) do
        bin.install "mllpong"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_darwin_arm64.tar.gz"
      sha256 "efb1deeb7d4067a8687c84fa6e946d4fc84298e20e834b0405857ca1786b23e7"

      define_method(:install) do
        bin.install "mllpong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_linux_amd64.tar.gz"
      sha256 "85ec3151f98c14456fbcc5780b48b7a790d4235418ab2c11632a0d43f6b707e7"
      define_method(:install) do
        bin.install "mllpong"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_linux_arm64.tar.gz"
      sha256 "ba3e78d3087874ecdb396008b717b9d01f33cc3a287b35d5283b17a4b5df06d4"
      define_method(:install) do
        bin.install "mllpong"
      end
    end
  end
end
