# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mllpong < Formula
  desc "A lightweight mock server for HL7 v2 messages over MLLP — always-ACK, always-NACK, and rule-based smart handler"
  homepage "https://mllpong.novalagung.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_darwin_amd64.tar.gz"
      sha256 "d4220289f268e7170cf8560658732eb219b14e49b4e6fa87ec7313ec15b6461e"

      define_method(:install) do
        bin.install "mllpong"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_darwin_arm64.tar.gz"
      sha256 "1bb0a848d364f47bfc88a9e052361c20e711284ed14a5c0bb7108c2e2cf138ba"

      define_method(:install) do
        bin.install "mllpong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_linux_amd64.tar.gz"
      sha256 "426b71c009d0bcfb2f3436be4d8edefd8378180083a42c289f3cdac94b851151"
      define_method(:install) do
        bin.install "mllpong"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/novalagung/mllpong/releases/download/v1.0.0/mllpong_linux_arm64.tar.gz"
      sha256 "bc3f1e5cbf6fdd164009a95564838a31ddde33988ea83f052e92524778e7e59e"
      define_method(:install) do
        bin.install "mllpong"
      end
    end
  end
end
