# This file was generated by GoReleaser. DO NOT EDIT.
cask "mllpong" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "c2e1713ef3bd37b6fbb44f5a46c8277f4a12bbf11a2c1da0735fd96f1ca956a3"
      url "https://github.com/novalagung/mllpong/releases/download/v#{version}/mllpong_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4980e9774927be38ed5d8a0fa14ecb4d11db096ecc03cd53679bbecd666b1d7e"
      url "https://github.com/novalagung/mllpong/releases/download/v#{version}/mllpong_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dcede7b43f8c92892b8d4dae5dbc86ff537454e21e2e8fd64a261314d8ec6280"
      url "https://github.com/novalagung/mllpong/releases/download/v#{version}/mllpong_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e2f084b078e79472feef5a8b029b8fdb22e54f5f94d62666193ce2353bc3d19"
      url "https://github.com/novalagung/mllpong/releases/download/v#{version}/mllpong_linux_amd64.tar.gz"
    end
  end

  name "mllpong"
  desc "An open-source lightweight mock server for testing HL7 v2 messages over MLLP — always-ACK, always-NACK, and rule-based smart handler"
  homepage "https://mllpong.novalagung.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mllpong"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mllpong"]
    end
  end

  # No zap stanza required
end
